/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TiendaAbarrotes;

import java.sql.Connection;
import javax.swing.JTable;
/**
 *
 * @author Luis Bacasehua
 */
public class jfDetalleDevolucion extends javax.swing.JFrame {

    private Connection conexion;

    private DetalleDevolucion detalleDevolucion;
    /**
     * Creates new form jfDetalleDevolucion
     */
    public jfDetalleDevolucion() {
        initComponents();
    }

    
        public void asignaConexion(Connection connection) {
        this.conexion = connection;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMotivoDevEntrega = new javax.swing.JLabel();
        jLProductoDetalleDev = new javax.swing.JLabel();
        jCMotivoDevolucionDetalle = new javax.swing.JComboBox<>();
        jCProductoDetalle = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTDetallesDevoluciones = new javax.swing.JTable();
        jBAgregarDetalleDev = new javax.swing.JButton();
        jBEditarDetalleDev = new javax.swing.JButton();
        jBEliminarDetalleDev = new javax.swing.JButton();
        jLCantidad = new javax.swing.JLabel();
        jTCantidadDetalleDev = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jMotivoDevEntrega.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jMotivoDevEntrega.setForeground(new java.awt.Color(0, 102, 153));
        jMotivoDevEntrega.setText("Motivo devolución:");

        jLProductoDetalleDev.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLProductoDetalleDev.setForeground(new java.awt.Color(0, 102, 153));
        jLProductoDetalleDev.setText("Producto:");

        jCMotivoDevolucionDetalle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jCProductoDetalle.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        jTDetallesDevoluciones.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N
        jTDetallesDevoluciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTDetallesDevolucionesMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTDetallesDevoluciones);

        jBAgregarDetalleDev.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBAgregarDetalleDev.setForeground(new java.awt.Color(0, 153, 153));
        jBAgregarDetalleDev.setText("Insertar");
        jBAgregarDetalleDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAgregarDetalleDevActionPerformed(evt);
            }
        });

        jBEditarDetalleDev.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEditarDetalleDev.setForeground(new java.awt.Color(0, 153, 153));
        jBEditarDetalleDev.setText("Modificar");
        jBEditarDetalleDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEditarDetalleDevActionPerformed(evt);
            }
        });

        jBEliminarDetalleDev.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jBEliminarDetalleDev.setForeground(new java.awt.Color(0, 153, 153));
        jBEliminarDetalleDev.setText("Eliminar");
        jBEliminarDetalleDev.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEliminarDetalleDevActionPerformed(evt);
            }
        });

        jLCantidad.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLCantidad.setForeground(new java.awt.Color(0, 102, 153));
        jLCantidad.setText("Cantidad:");

        jTCantidadDetalleDev.setFont(new java.awt.Font("Arial", 0, 12)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLProductoDetalleDev, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jMotivoDevEntrega, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(2, 2, 2)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jCProductoDetalle, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jCMotivoDevolucionDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(57, 57, 57)
                        .addComponent(jLCantidad)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTCantidadDetalleDev, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(122, 122, 122))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(135, 135, 135)
                        .addComponent(jBAgregarDetalleDev)
                        .addGap(75, 75, 75)
                        .addComponent(jBEditarDetalleDev)
                        .addGap(79, 79, 79)
                        .addComponent(jBEliminarDetalleDev)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCMotivoDevolucionDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTCantidadDetalleDev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jMotivoDevEntrega)
                    .addComponent(jLCantidad))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCProductoDetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLProductoDetalleDev))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBAgregarDetalleDev, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEditarDetalleDev, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBEliminarDetalleDev, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        detalleDevolucion = new DetalleDevolucion();
        detalleDevolucion.consultaDetallesDevolucion(conexion, jTDetallesDevoluciones);
        detalleDevolucion.cargaMotivoDevoluciones(conexion, jCMotivoDevolucionDetalle);
        detalleDevolucion.cargaProductos(conexion, jCProductoDetalle);
    }//GEN-LAST:event_formWindowOpened

    private void jTDetallesDevolucionesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTDetallesDevolucionesMouseClicked
        // TODO add your handling code here:
        JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        detalleDevolucion.setIdDetalleDevolucion(Integer.parseInt(source.getModel().getValueAt(row, 0).toString()));
        jCMotivoDevolucionDetalle.setSelectedItem(new Item(Integer.parseInt(source.getModel().getValueAt(row, 1).toString())));
        jCProductoDetalle.setSelectedItem(new Item(Integer.parseInt(source.getModel().getValueAt(row, 2).toString())));
        jTCantidadDetalleDev.setText(source.getModel().getValueAt(row, 3).toString());
     
    }//GEN-LAST:event_jTDetallesDevolucionesMouseClicked

    private void jBAgregarDetalleDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAgregarDetalleDevActionPerformed
        // TODO add your handling code here:
        int idMotivo = ((Item) jCMotivoDevolucionDetalle.getSelectedItem()).getId();
        int idProducto = ((Item) jCProductoDetalle.getSelectedItem()).getId();
        int cantidad = Integer.parseInt(jTCantidadDetalleDev.getText());
        detalleDevolucion.agregaDetalleDevolucion(conexion, idMotivo, idProducto, cantidad);
        detalleDevolucion.consultaDetallesDevolucion(conexion, jTDetallesDevoluciones);
        resetControles();
    }//GEN-LAST:event_jBAgregarDetalleDevActionPerformed

    private void jBEditarDetalleDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEditarDetalleDevActionPerformed
        // TODO add your handling code here:
        int idMotivo = ((Item) jCMotivoDevolucionDetalle.getSelectedItem()).getId();
        int idProducto = ((Item) jCProductoDetalle.getSelectedItem()).getId();
        int cantidad = Integer.parseInt(jTCantidadDetalleDev.getText());
        detalleDevolucion.modificaDetalleDevolucion(conexion, idMotivo, idProducto, cantidad);
        detalleDevolucion.consultaDetallesDevolucion(conexion, jTDetallesDevoluciones);
        resetControles();
    }//GEN-LAST:event_jBEditarDetalleDevActionPerformed

    private void jBEliminarDetalleDevActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEliminarDetalleDevActionPerformed
        // TODO add your handling code here:
        detalleDevolucion.eliminaEntrega(conexion);
        detalleDevolucion.consultaDetallesDevolucion(conexion, jTDetallesDevoluciones);        
        resetControles();
    }//GEN-LAST:event_jBEliminarDetalleDevActionPerformed
    
    public void resetControles() {
        jCMotivoDevolucionDetalle.setSelectedItem(null);
        jCProductoDetalle.setSelectedItem(null);
        jTCantidadDetalleDev.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(jfDetalleDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(jfDetalleDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(jfDetalleDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(jfDetalleDevolucion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new jfDetalleDevolucion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAgregarDetalleDev;
    private javax.swing.JButton jBEditarDetalleDev;
    private javax.swing.JButton jBEliminarDetalleDev;
    private javax.swing.JComboBox<String> jCMotivoDevolucionDetalle;
    private javax.swing.JComboBox<String> jCProductoDetalle;
    private javax.swing.JLabel jLCantidad;
    private javax.swing.JLabel jLProductoDetalleDev;
    private javax.swing.JLabel jMotivoDevEntrega;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTCantidadDetalleDev;
    private javax.swing.JTable jTDetallesDevoluciones;
    // End of variables declaration//GEN-END:variables
}
