/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TiendaAbarrotes;

import java.sql.Connection;
import java.util.List;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonia Hernandez
 */
public class JFDetalleCompra extends javax.swing.JFrame {

    private Connection conexion = null;
    private DetalleCompra detalleCompra;
    private DefaultTableModel modelo;
    private Statement st;
    private PreparedStatement pt;
    private ResultSet rs;
    private String Qry;
    private String idRow;
    private List<String> compras;
    private List<String[]> productos;
    
    public JFDetalleCompra() {
        initComponents();
        LlenaComboBox();
        detalleCompra = new DetalleCompra(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbCompraDetalleCompra = new javax.swing.JLabel();
        cbCompraDetalleCompra = new javax.swing.JComboBox<>();
        lbProductoDetalleCompra = new javax.swing.JLabel();
        cbProductoDetalleCompra = new javax.swing.JComboBox<>();
        lbCantidadDetalleCompra = new javax.swing.JLabel();
        tfCantidadDetalleCompra = new javax.swing.JTextField();
        lbSubtotalDetalleCompra = new javax.swing.JLabel();
        tfSubtotalDetalleCompra = new javax.swing.JTextField();
        btInsertarDetalleCompra = new javax.swing.JButton();
        btModificarDetalleCompra = new javax.swing.JButton();
        btEliminarDetalleCompra = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableDetalleCompra = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbCompraDetalleCompra.setText("Compra:");

        cbCompraDetalleCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbProductoDetalleCompra.setText("Producto:");

        cbProductoDetalleCompra.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lbCantidadDetalleCompra.setText("Cantidad:");

        lbSubtotalDetalleCompra.setText("Subtotal:");

        btInsertarDetalleCompra.setText("Insertar");
        btInsertarDetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertarDetalleCompraActionPerformed(evt);
            }
        });

        btModificarDetalleCompra.setText("Modificar");
        btModificarDetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarDetalleCompraActionPerformed(evt);
            }
        });

        btEliminarDetalleCompra.setText("Eliminar");
        btEliminarDetalleCompra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarDetalleCompraActionPerformed(evt);
            }
        });

        tableDetalleCompra.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableDetalleCompra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDetalleCompraMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableDetalleCompra);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbCompraDetalleCompra)
                                    .addComponent(lbCantidadDetalleCompra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(cbCompraDetalleCompra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(tfCantidadDetalleCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbProductoDetalleCompra)
                                    .addComponent(lbSubtotalDetalleCompra))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(tfSubtotalDetalleCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE)
                                    .addComponent(cbProductoDetalleCompra, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btInsertarDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btModificarDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(75, 75, 75)
                        .addComponent(btEliminarDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(36, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCompraDetalleCompra)
                    .addComponent(lbProductoDetalleCompra)
                    .addComponent(cbCompraDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbProductoDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCantidadDetalleCompra)
                    .addComponent(tfCantidadDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSubtotalDetalleCompra)
                    .addComponent(tfSubtotalDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsertarDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificarDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminarDetalleCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsertarDetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertarDetalleCompraActionPerformed
        String idProducto = "";
        
        for(int i = 0; i < productos.size(); i++)
        {
            if(productos.get(i)[1] == (String)cbProductoDetalleCompra.getSelectedItem())
            {
                idProducto = productos.get(i)[0];
            }
        }
        detalleCompra.InsertaDetalleCompra((String)cbCompraDetalleCompra.getSelectedItem(), idProducto, tfCantidadDetalleCompra.getText(), tfSubtotalDetalleCompra.getText());
        ActualizaTablaDetalleCompra();
    }//GEN-LAST:event_btInsertarDetalleCompraActionPerformed

    private void btModificarDetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarDetalleCompraActionPerformed
        String idProducto = "";
        
        for(int i = 0; i < productos.size(); i++)
        {
            if(productos.get(i)[1] == (String)cbProductoDetalleCompra.getSelectedItem())
            {
                idProducto = productos.get(i)[0];
            }
        }
        detalleCompra.ModificaDetalleCompra((String)cbCompraDetalleCompra.getSelectedItem(), idProducto, tfCantidadDetalleCompra.getText(), tfSubtotalDetalleCompra.getText(), idRow);
        ActualizaTablaDetalleCompra();
    }//GEN-LAST:event_btModificarDetalleCompraActionPerformed

    private void btEliminarDetalleCompraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarDetalleCompraActionPerformed
        detalleCompra.EliminaDetalleCompra(idRow);
        ActualizaTablaDetalleCompra();
    }//GEN-LAST:event_btEliminarDetalleCompraActionPerformed

    private void tableDetalleCompraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDetalleCompraMouseClicked
        String i = (String)tableDetalleCompra.getValueAt(tableDetalleCompra.getSelectedRow(), 0);
        //javax.swing.JOptionPane.showMessageDialog(this, i);
        idRow = i;
        cbCompraDetalleCompra.setSelectedItem((Item)tableDetalleCompra.getValueAt(tableDetalleCompra.getSelectedRow(), 1));
        cbProductoDetalleCompra.setSelectedItem((Item)tableDetalleCompra.getValueAt(tableDetalleCompra.getSelectedRow(), 2));
        tfCantidadDetalleCompra.setText((String)tableDetalleCompra.getValueAt(tableDetalleCompra.getSelectedRow(), 3));
        tfSubtotalDetalleCompra.setText((String)tableDetalleCompra.getValueAt(tableDetalleCompra.getSelectedRow(), 4));
    }//GEN-LAST:event_tableDetalleCompraMouseClicked

    public void LlenaComboBox()
    {
        try {
            Qry = "SELECT IdCompra FROM Transaccion.Compra";
            st = conexion.createStatement();
            rs = st.executeQuery(Qry);
            String Aux;
            while(rs.next()) {
                Aux = rs.getString(1);
                compras.add(Aux);
            }
        }
        catch(Exception e) {
            
        }
        
        try {
            Qry = "SELECT IdProducto, Nombre FROM Inventario.Producto";
            st = conexion.createStatement();
            rs = st.executeQuery(Qry);
            String Aux[] = new String[2];
            while(rs.next()) {
                Aux[0] = rs.getString(1);
                Aux[1] = rs.getString(2);
                productos.add(Aux);
            }
        }
        catch(Exception e) {
            
        }
        
        for(int i = 0; i < compras.size(); i++)
        {
            cbCompraDetalleCompra.addItem(compras.get(i));
        }
        for(int i = 0; i < productos.size(); i++)
        {
            cbProductoDetalleCompra.addItem(productos.get(i)[1]);
        }
        
    }
    
    public void AsignaConexion(Connection con)
    {
        conexion = con;
    }
    
    public void ActualizaTablaDetalleCompra()
    {
        modelo = new DefaultTableModel();
        modelo.addColumn("Id Compra");
        modelo.addColumn("Id Producto");
        modelo.addColumn("Cantidad");
        modelo.addColumn("Subtotal");
        
        try {
            Qry = "SELECT * FROM Transaccion.DetalleCompra";
            st = conexion.createStatement();
            rs = st.executeQuery(Qry);
            String Aux[] = new String[4];
            while(rs.next()) {
                Aux[0] = rs.getString(2);
                Aux[1] = rs.getString(3);
                Aux[2] = rs.getString(4);
                Aux[3] = rs.getString(5);
                modelo.addRow(Aux);
            }
            tableDetalleCompra.setModel(modelo);
        }
        catch(Exception e) {
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFDetalleCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFDetalleCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminarDetalleCompra;
    private javax.swing.JButton btInsertarDetalleCompra;
    private javax.swing.JButton btModificarDetalleCompra;
    private javax.swing.JComboBox<String> cbCompraDetalleCompra;
    private javax.swing.JComboBox<String> cbProductoDetalleCompra;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCantidadDetalleCompra;
    private javax.swing.JLabel lbCompraDetalleCompra;
    private javax.swing.JLabel lbProductoDetalleCompra;
    private javax.swing.JLabel lbSubtotalDetalleCompra;
    private javax.swing.JTable tableDetalleCompra;
    private javax.swing.JTextField tfCantidadDetalleCompra;
    private javax.swing.JTextField tfSubtotalDetalleCompra;
    // End of variables declaration//GEN-END:variables
}
