/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TiendaAbarrotes;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sonia Hernandez
 */
public class JFProducto extends javax.swing.JFrame {

    Connection conexion;
    Producto producto;
    private DefaultTableModel modelo;
    private Statement st;
    private PreparedStatement pt;
    private ResultSet rs;
    private String Qry;
    private String idRow;
    
    public JFProducto() {
        initComponents();
        producto = new Producto(conexion);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbNombreProducto = new javax.swing.JLabel();
        tfNombreProducto = new javax.swing.JTextField();
        lbExistenciaProducto = new javax.swing.JLabel();
        tfExistenciaProducto = new javax.swing.JTextField();
        lbCostoProvProducto = new javax.swing.JLabel();
        tfCostoProvProducto = new javax.swing.JTextField();
        lbCostoVentaProducto = new javax.swing.JLabel();
        tfCostoVentaProducto = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProducto = new javax.swing.JTable();
        btInsertarProducto = new javax.swing.JButton();
        btModificarProducto = new javax.swing.JButton();
        btEliminarProducto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        lbNombreProducto.setText("Nombre:");

        lbExistenciaProducto.setText("Existencia:");

        lbCostoProvProducto.setText("Costo proveedor:");

        lbCostoVentaProducto.setText("Costo venta:");

        tableProducto.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableProducto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProductoMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProducto);

        btInsertarProducto.setText("Insertar");
        btInsertarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btInsertarProductoActionPerformed(evt);
            }
        });

        btModificarProducto.setText("Modificar");
        btModificarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btModificarProductoActionPerformed(evt);
            }
        });

        btEliminarProducto.setText("Eliminar");
        btEliminarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEliminarProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNombreProducto, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lbCostoProvProducto))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(lbExistenciaProducto))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(tfCostoProvProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(lbCostoVentaProducto)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tfExistenciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(tfCostoVentaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 621, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(btInsertarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(85, 85, 85)
                        .addComponent(btModificarProducto)
                        .addGap(76, 76, 76)
                        .addComponent(btEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNombreProducto)
                    .addComponent(tfNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbExistenciaProducto)
                    .addComponent(tfExistenciaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCostoProvProducto)
                    .addComponent(tfCostoProvProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbCostoVentaProducto)
                    .addComponent(tfCostoVentaProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btInsertarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btModificarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEliminarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(47, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btInsertarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btInsertarProductoActionPerformed
        producto.InsertaProducto(conexion, tfNombreProducto.getText(), tfExistenciaProducto.getText(), tfCostoProvProducto.getText(), tfCostoVentaProducto.getText());
        resetControles();
        ActualizaTablaProducto();
    }//GEN-LAST:event_btInsertarProductoActionPerformed

    private void btModificarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btModificarProductoActionPerformed
        producto.ModificaProducto(conexion, tfNombreProducto.getText(), tfExistenciaProducto.getText(), tfCostoProvProducto.getText(), tfCostoVentaProducto.getText(), idRow);
        resetControles();
        ActualizaTablaProducto();
    }//GEN-LAST:event_btModificarProductoActionPerformed

    private void btEliminarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEliminarProductoActionPerformed
        producto.EliminaProducto(conexion,idRow);
        resetControles();       
        ActualizaTablaProducto();
    }//GEN-LAST:event_btEliminarProductoActionPerformed

    private void tableProductoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProductoMouseClicked
        
                JTable source = (JTable) evt.getSource();
        int row = source.rowAtPoint(evt.getPoint());
        producto.setIdProducto(Integer.parseInt(source.getModel().getValueAt(row, 0).toString()));
        tfNombreProducto.setText((String)tableProducto.getValueAt(tableProducto.getSelectedRow(), 1));
        tfExistenciaProducto.setText((String)tableProducto.getValueAt(tableProducto.getSelectedRow(), 2));
        tfCostoProvProducto.setText((String)tableProducto.getValueAt(tableProducto.getSelectedRow(), 3));
        tfCostoVentaProducto.setText((String)tableProducto.getValueAt(tableProducto.getSelectedRow(), 4));
    }//GEN-LAST:event_tableProductoMouseClicked

    private void resetControles(){
        tfNombreProducto.setText("");
        tfExistenciaProducto.setText("");
        tfCostoProvProducto.setText("");
        tfCostoVentaProducto.setText("");
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

        // TODO add your handling code here:
        ActualizaTablaProducto();
    }//GEN-LAST:event_formWindowOpened

    public void AsignaConexion(Connection con)
    {
        conexion = con;
    }
    
    public void ActualizaTablaProducto()
    {
        modelo = new DefaultTableModel();
        modelo.addColumn("Id Producto");
        modelo.addColumn("Nombre");
        modelo.addColumn("Existencia");
        modelo.addColumn("Costo proveedor");
        modelo.addColumn("Costo venta");
        
        try {
            Qry = "SELECT * FROM Inventario.Producto";
            st = conexion.createStatement();
            rs = st.executeQuery(Qry);
            String Aux[] = new String[5];
            while(rs.next()) {
                Aux[0] = rs.getString(1);
                Aux[1] = rs.getString(2);
                Aux[2] = rs.getString(3);
                Aux[3] = rs.getString(4);
                Aux[4] = rs.getString(5);
                modelo.addRow(Aux);
            }
            tableProducto.setModel(modelo);
        }
        catch(Exception e) {
            
        }
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFProducto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFProducto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEliminarProducto;
    private javax.swing.JButton btInsertarProducto;
    private javax.swing.JButton btModificarProducto;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbCostoProvProducto;
    private javax.swing.JLabel lbCostoVentaProducto;
    private javax.swing.JLabel lbExistenciaProducto;
    private javax.swing.JLabel lbNombreProducto;
    private javax.swing.JTable tableProducto;
    private javax.swing.JTextField tfCostoProvProducto;
    private javax.swing.JTextField tfCostoVentaProducto;
    private javax.swing.JTextField tfExistenciaProducto;
    private javax.swing.JTextField tfNombreProducto;
    // End of variables declaration//GEN-END:variables
}
