/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package TiendaAbarrotes;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;

/**
 *
 * @author Luis Bacasehua
 */
public class Menu2 extends javax.swing.JFrame {

    private Connection conexion;

    /**
     * Creates new form Menu2
     */
    public Menu2(Connection conexion) {
        initComponents();
        this.conexion = conexion;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JbEmpleadoMenu = new javax.swing.JButton();
        jBProveedorMenu = new javax.swing.JButton();
        jBProductoMenu = new javax.swing.JButton();
        jBPromocionMenu = new javax.swing.JButton();
        jBVentaMenu = new javax.swing.JButton();
        jBDetalleVentaMenu = new javax.swing.JButton();
        jBCompraMenu = new javax.swing.JButton();
        jBDetalleCompraMEnu = new javax.swing.JButton();
        jBDevolucion = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jBEntregaMenu = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        JbEmpleadoMenu.setText("Empleado");
        JbEmpleadoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbEmpleadoMenuActionPerformed(evt);
            }
        });

        jBProveedorMenu.setText("Proveedor");
        jBProveedorMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProveedorMenuActionPerformed(evt);
            }
        });

        jBProductoMenu.setText("Producto");
        jBProductoMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBProductoMenuActionPerformed(evt);
            }
        });

        jBPromocionMenu.setText("Promocion");
        jBPromocionMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPromocionMenuActionPerformed(evt);
            }
        });

        jBVentaMenu.setText("Venta");
        jBVentaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBVentaMenuActionPerformed(evt);
            }
        });

        jBDetalleVentaMenu.setText("Detalle Venta");
        jBDetalleVentaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetalleVentaMenuActionPerformed(evt);
            }
        });

        jBCompraMenu.setText("Compra");
        jBCompraMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBCompraMenuActionPerformed(evt);
            }
        });

        jBDetalleCompraMEnu.setText("Detalle Compra");
        jBDetalleCompraMEnu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDetalleCompraMEnuActionPerformed(evt);
            }
        });

        jBDevolucion.setText("Devolución");
        jBDevolucion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBDevolucionActionPerformed(evt);
            }
        });

        jButton1.setText("Detalle Devolución");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jBEntregaMenu.setText("Entrega");
        jBEntregaMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBEntregaMenuActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(JbEmpleadoMenu)
                        .addGap(31, 31, 31)
                        .addComponent(jBProveedorMenu)
                        .addGap(18, 18, 18)
                        .addComponent(jBProductoMenu)
                        .addGap(33, 33, 33)
                        .addComponent(jBPromocionMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBVentaMenu)
                            .addComponent(jBCompraMenu))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jBDetalleCompraMEnu)
                            .addComponent(jBDetalleVentaMenu)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jBDevolucion)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jBEntregaMenu))
                .addContainerGap(106, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JbEmpleadoMenu)
                    .addComponent(jBProveedorMenu)
                    .addComponent(jBProductoMenu)
                    .addComponent(jBPromocionMenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBVentaMenu)
                    .addComponent(jBDetalleVentaMenu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBCompraMenu)
                    .addComponent(jBDetalleCompraMEnu))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBDevolucion)
                    .addComponent(jButton1))
                .addGap(18, 18, 18)
                .addComponent(jBEntregaMenu)
                .addContainerGap(148, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void JbEmpleadoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbEmpleadoMenuActionPerformed
        // TODO add your handling code here:
        JFEmpleado empleado = new JFEmpleado();
        empleado.AsignaConexion(conexion);
        empleado.setVisible(true);
    }//GEN-LAST:event_JbEmpleadoMenuActionPerformed

    private void jBProveedorMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProveedorMenuActionPerformed
        // TODO add your handling code here:
        jfProveedor proveedorFrame = new jfProveedor();
        proveedorFrame.asignaConexion(conexion);
        proveedorFrame.setVisible(true);
    }//GEN-LAST:event_jBProveedorMenuActionPerformed

    private void jBProductoMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBProductoMenuActionPerformed
        // TODO add your handling code here:
        JFProducto producto = new JFProducto();
        producto.AsignaConexion(conexion);
        producto.setVisible(true);
    }//GEN-LAST:event_jBProductoMenuActionPerformed

    private void jBPromocionMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPromocionMenuActionPerformed
        // TODO add your handling code here:
        jfPromocion promocionFrame = new jfPromocion();
        promocionFrame.asignaConexion(conexion);
        promocionFrame.setVisible(true);
    }//GEN-LAST:event_jBPromocionMenuActionPerformed

    private void jBVentaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBVentaMenuActionPerformed
        // TODO add your handling code here:
        jfVenta ventaFrame = new jfVenta();
        ventaFrame.asignaConexion(conexion);
        ventaFrame.setVisible(true);
    }//GEN-LAST:event_jBVentaMenuActionPerformed

    private void jBDetalleVentaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetalleVentaMenuActionPerformed
        // TODO add your handling code here:
        jfDetalleVenta detalleFrame = new jfDetalleVenta();
        detalleFrame.asignaConexion(conexion);
        detalleFrame.setVisible(true);
    }//GEN-LAST:event_jBDetalleVentaMenuActionPerformed

    private void jBCompraMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBCompraMenuActionPerformed
        // TODO add your handling code here:
        JFCompra compra = new JFCompra();
        compra.AsignaConexion(conexion);
        compra.setVisible(true);
    }//GEN-LAST:event_jBCompraMenuActionPerformed

    private void jBDetalleCompraMEnuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDetalleCompraMEnuActionPerformed
        // TODO add your handling code here:
        JFDetalleCompra detalleCompra = new JFDetalleCompra();
        detalleCompra.AsignaConexion(conexion);
        detalleCompra.setVisible(true);
    }//GEN-LAST:event_jBDetalleCompraMEnuActionPerformed

    private void jBDevolucionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBDevolucionActionPerformed
        // TODO add your handling code here:
        jfDevolucion devolucionFrame = new jfDevolucion();
        devolucionFrame.asignaConexion(conexion);
        devolucionFrame.setVisible(true);
    }//GEN-LAST:event_jBDevolucionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        jfDetalleDevolucion detalleDevolucionFrame = new jfDetalleDevolucion();
        detalleDevolucionFrame.asignaConexion(conexion);
        detalleDevolucionFrame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jBEntregaMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBEntregaMenuActionPerformed
        // TODO add your handling code here:
        jfEntrega entregaFrame = new jfEntrega(conexion);
        entregaFrame.asignaConexion(conexion);
        entregaFrame.setVisible(true);
    }//GEN-LAST:event_jBEntregaMenuActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        /*conexion = null;
        conectaBD();*/
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new Menu2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton JbEmpleadoMenu;
    private javax.swing.JButton jBCompraMenu;
    private javax.swing.JButton jBDetalleCompraMEnu;
    private javax.swing.JButton jBDetalleVentaMenu;
    private javax.swing.JButton jBDevolucion;
    private javax.swing.JButton jBEntregaMenu;
    private javax.swing.JButton jBProductoMenu;
    private javax.swing.JButton jBPromocionMenu;
    private javax.swing.JButton jBProveedorMenu;
    private javax.swing.JButton jBVentaMenu;
    private javax.swing.JButton jButton1;
    // End of variables declaration//GEN-END:variables
}
